spring:
  application.name: experimentspb-mongo
  profiles.active: devTest
#  data.mongodb.uri: mongodb://swgd:easipass@106.14.83.136:27017/swgd
  data.mongodb.uri: mongodb://mock:easipass@106.14.83.136:27017/mock
server:
  port: 9091